export const FETCH_WORLD_STATS = 'FETCH_WORLD_STATS';
export const FETCH_SELECTED_COUNTRY_STATS = 'FETCH_SELECTED_COUNTRY_STATS';
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const SET_COUNTRIES = 'SET_COUNTRIES';
export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';
export const FETCH_WORLD_DAILY_DATA = 'FETCH_WORLD_DAILY_DATA';
